const UserActionTypes = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  GET_INFORMACAO_PESSOAL_START: "GET_INFORMACAO_PESSOAL_START",
  GET_INFORMACAO_PESSOAL_SUCCESS: "GET_INFORMACAO_PESSOAL_SUCCESS",
  GET_INFORMACAO_PESSOAL_FAILURE: "GET_INFORMACAO_PESSOAL_FAILURE",

  FINALIZAR_COMPRA_START: "FINALIZAR_COMPRA_START",
  FINALIZAR_COMPRA_SUCCESS: "FINALIZAR_COMPRA_SUCCESS",
  FINALIZAR_COMPRA_FAILURE: "FINALIZAR_COMPRA_FAILURE",

  RECUPERAR_COMPRAS_START: "RECUPERAR_COMPRAS_START",
  RECUPERAR_COMPRAS_SUCCESS: "RECUPERAR_COMPRAS_SUCCESS",
  RECUPERAR_COMPRAS_FAILURE: "RECUPERAR_COMPRAS_FAILURE",
};

export default UserActionTypes;
