const ProdutoActionTypes = {
  GET_PRODUTO_START: "GET_PRODUTO_START",
  GET_PRODUTO_SUCCESS: "GET_PRODUTO_SUCCESS",
  GET_PRODUTO_FAILURE: "GET_PRODUTO_FAILURE",

  GET_PRODUTOS_START: "GET_PRODUTOS_START",
  GET_PRODUTOS_SUCCESS: "GET_PRODUTOS_SUCCESS",
  GET_PRODUTOS_FAILURE: "GET_PRODUTOS_FAILURE",
};

export default ProdutoActionTypes;
