const ColecaoActionTypes = {
  GET_COLECAO_START: "GET_COLECAO_START",
  GET_COLECAO_SUCCESS: "GET_COLECAO_SUCCESS",
  GET_COLECAO_FAILURE: "GET_COLECAO_FAILURE",
};

export default ColecaoActionTypes;
