const ColecaoActionTypes = {
  GET_COLECAO_START: "GET_COLECAO_START",
  GET_COLECAO_SUCCESS: "GET_COLECAO_SUCCESS",
  GET_COLECAO_FAILURE: "GET_COLECAO_FAILURE",
  GET_COLECAO_DE_LOJA_START: "GET_COLECAO_DE_LOJA_START",
  GET_COLECAO_DE_LOJA_SUCCESS: "GET_COLECAO_DE_LOJA_SUCCESS",
  GET_COLECAO_DE_LOJA_FAILURE: "GET_COLECAO_DE_LOJA_FAILURE",
  GET_PRODUTOS_DE_COLECAO_START: "GET_PRODUTOS_DE_COLECAO_START",
  GET_PRODUTOS_DE_COLECAO_SUCCESS: "GET_PRODUTOS_DE_COLECAO_SUCCESS",
  GET_PRODUTOS_DE_COLECAO_FAILURE: "GET_PRODUTOS_DE_COLECAO_FAILURE",
};

export default ColecaoActionTypes;
